#!/bin/bash

# 2013-08-26
# Stop enterprise subscription notification from showing up before login. version 3.1
sed -i "/if (data.status !== 'Active')/i\ data.status = 'Active';" /usr/share/pve-manager/ext4/pvemanagerlib.js
